### ISSUE TITLE
Completed Homework

### ISSUE THREAD

**Issue by pbrandstetter** [htl-perg-2019-20-5bhif/highscore-exercise-pbrandstetter#1]
Dear Mr. Stropek,

I created an API, the Highscore List in the frontend and two Dockerfiles.
I hope that I fulfilled all requirements.

Sincerely,
Philipp Brandstetter

**Comment by rstropek** [comment]
Hi @pbrandstetter!

Well done 👍. I especially like the classic Arcade-like display of the highscore list 😎. You get two extra points for the exercise (one for POSE and one for NVS MC.

Greetings,
Rainer Stropek.
